language: node_js
dist: trusty
node_js:
  - 'node'
  - 'lts/*'

script:
  - npm run test
  - npm run build
  - sonar-scanner -X

before_install:
  - cd Videogames
  - npm install

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "alu0101015927"
    token:
      secure: "ixt323HeH6dSWyaJm3QiYHQ+aoh6BQI3m9xbeUUU4UQzvaUTCt6dH8LqQ7nj3tW4kg4Pp+6PCx7kYZNT9C2LsoWlGw24jpWmpcwWGDdCMQ37wZs1v6A7jFxHOik1bABdS5J+H29Cv2x5slBVQkl3KUbgEEebN+Of8FX80h7GySUs3pRtcm9xUOSFuNGihMXHxtyYNkgsETyWXTxfe7ijOj39ZWwSUstzyKEHhnK54n2P85d+Jfdsg4MKf+QYvn5M9bC/6RdzuJ1+5IMROxCwDQjOn0GHQts8NtIWr4k7RQQxPeS8akvtp3Z3LWy9D9ShkZNezNVo7Ru6jvl5FcKUDUxFlKZGgMfvCGsMN8SLyNIsK2R7H4jMYL8vZzN9Rj3egtOdkjBe46UNd6FbLQjp/kaHALN0MIBa+m7Ve3OOf/njFc3T743AkS60Rw3AR6uZTLeLeiqbH3fuRibDPG8OE61KINeCngzLE/eaiPISTgSVL4J5iJWcuwtfSy7YgVHp54QKbn166uIVimvMdmEbkqSAaciqitpc/D+fe7O5Xxtgi0j4N4gTv233bJVDLmHjGu1IXPF10B6wPvGPJMKfOSETMHUIGNE/PQlR4W3lYkUKGiR7yYdBLdO5lNzB27nIKHTgCVpe5oYpGvcW9V/kazRIseRutNGMI1GuWYle6nE="
      # secure: ${SONAR_TOKEN}
