language: node_js

node_js:
  - 'node'
  - 'lts/*'

script:
  - npm run test
  - npm run build

before_install:
  - cd Videogames
  - npm install

notifications:
  slack: 'sytw:zOwATE9j5xq2yo6Jqb8y6YtR#e02'
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
