language: node_js

node_js:
  - 'node'
  - 'lts/*'

addons:
  sonarcloud:
    organization: "sytw2019"
    token:
      secure: ${SONAR_TOKEN}
      
script:
  - npm run test
  - npm run build
  - sonar-scanner

before_install:
  - cd Videogames
  - npm install

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
