language: node_js

node_js:
  - 'node'
  - 'lts/*'

addons:
  sonarcloud:
    organization: "sytw2019" # the key of the org you chose at step #3
    token: 2daae18682f662535c600a6e435650eef789b62b

script:
  - npm run test
  - npm run build
  - sonar-scanner
  
before_install:
  - cd Videogames
  - npm install

notifications:
  slack: 'sytw:zOwATE9j5xq2yo6Jqb8y6YtR#2019-e02'
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
