language: node_js
dist: trusty
node_js:
  - 'node'
  - 'lts/*'
      
script:
  - npm run test
  - npm run build
  - sonar-scanner -X

before_install:
  - cd Xgames/Frontend/
  - npm install
notifications:
  slack: proyecto-sytw:cVWM9OYylOMopcZIydrXs9yf
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
    
addons:
  sonarcloud:
    organization: "sytw2019"
    token:
      secure: ${PRUEBA} 
