language: node_js

node_js:
  - "stable"
  - 'node'
  - 'lts/*'

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  domain: <my_name_here>.surge.sh
  project: ./build/
on:
  branch: travis

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change
  slack: 'sytw:zOwATE9j5xq2yo6Jqb8y6YtR#e02'

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
